spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems?useSSL=false
    username: root
    password: ""
  jpa:
    hibernate:
      ddl_auto: create
server:
  port: 8081
# Enable debug logging
logging:
  level:
    root: DEBUG